workflows:
  n-android-release:
    name: N Android Release
    max_build_duration: 30

    environment:
      flutter: stable

    scripts:
      - name: Prepare Flutter project
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: Analyze Dart code
        script: |
          flutter analyze

      - name: Build release APK
        script: |
          flutter build apk --release --android-skip-build-dependency-validation

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    
