name: Extract N project

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          rm -rf android lib pubspec.yaml codemagic.yaml README.md
          unzip -o N_complete_ready.zip
          cp -r N_complete_build/* .
          rm -rf N_complete_build
          rm N_complete_ready.zip

      - name: Commit project
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Prepare N project" || echo "Nothing to commit"
          git push
